//! DankMaterialShell (DMS) integration for smellytype
//!
//! Generates a QML plugin widget that displays smellytype status in DankMaterialShell.

use std::fs;
use std::io::{self, Write};
use std::path::PathBuf;

use crate::error::SmellyTypeError;
use crate::setup::get_smellytype_path;

/// Get the DMS plugins directory (~/.config/DankMaterialShell/plugins/)
fn get_plugins_dir() -> PathBuf {
    directories::BaseDirs::new()
        .map(|d| {
            d.config_dir()
                .join("DankMaterialShell")
                .join("plugins")
                .to_path_buf()
        })
        .unwrap_or_else(|| {
            std::env::var("HOME")
                .map(|h| {
                    PathBuf::from(h)
                        .join(".config")
                        .join("DankMaterialShell")
                        .join("plugins")
                })
                .unwrap_or_else(|_| PathBuf::from(".config/DankMaterialShell/plugins"))
        })
}

/// Get the SmellyTypeWidget plugin directory
fn get_widget_dir() -> PathBuf {
    get_plugins_dir().join("SmellyTypeWidget")
}

/// Get the QML file path
fn get_qml_path() -> PathBuf {
    get_widget_dir().join("SmellyType.qml")
}

/// The QML template with SMELLYTYPE_PATH as a placeholder
const QML_TEMPLATE: &str = r##"import QtQuick
import QtQuick.Layouts
import QtQuick.Controls

// SmellyType Status Widget for DankMaterialShell
// Generated by: smellytype setup dms
// Polls smellytype status every 500ms and displays state with icons

Item {
    id: smellytypeWidget
    implicitWidth: statusText.implicitWidth + 16
    implicitHeight: 32

    property string currentState: "stopped"
    property string statusIcon: "\uf131"  // mic-slash (stopped)
    property color statusColor: "#6272a4"

    // State to icon/color mapping (Nerd Font icons)
    readonly property var stateConfig: ({
        "idle": { icon: "\uf130", color: "#50fa7b" },      // mic (green)
        "recording": { icon: "\uf111", color: "#ff5555" }, // dot (red)
        "transcribing": { icon: "\uf110", color: "#f1fa8c" }, // spinner (yellow)
        "stopped": { icon: "\uf131", color: "#6272a4" }    // mic-slash (gray)
    })

    Timer {
        id: pollTimer
        interval: 500
        running: true
        repeat: true
        onTriggered: {
            statusProcess.start("SMELLYTYPE_PATH", ["status"])
        }
    }

    Process {
        id: statusProcess
        onReadyReadStandardOutput: {
            var output = readAllStandardOutput().toString().trim()
            if (output && output !== currentState) {
                currentState = output
                var config = stateConfig[currentState] || stateConfig["stopped"]
                statusIcon = config.icon
                statusColor = config.color
            }
        }
    }

    RowLayout {
        anchors.fill: parent
        spacing: 4

        Text {
            id: statusText
            text: statusIcon
            font.family: "Symbols Nerd Font"
            font.pixelSize: 14
            color: statusColor
            Layout.alignment: Qt.AlignVCenter

            // Pulse animation for recording state
            SequentialAnimation on opacity {
                running: currentState === "recording"
                loops: Animation.Infinite
                NumberAnimation { to: 0.5; duration: 500; easing.type: Easing.InOutQuad }
                NumberAnimation { to: 1.0; duration: 500; easing.type: Easing.InOutQuad }
            }
        }
    }

    MouseArea {
        id: mouseArea
        anchors.fill: parent
        hoverEnabled: true
        onClicked: {
            // Toggle recording on click
            toggleProcess.start("SMELLYTYPE_PATH", ["record", "toggle"])
        }
    }

    Process {
        id: toggleProcess
    }

    // Tooltip
    ToolTip {
        visible: mouseArea.containsMouse
        text: {
            switch (currentState) {
                case "recording": return "Recording... (click to stop)"
                case "transcribing": return "Transcribing..."
                case "idle": return "SmellyType ready (click to record)"
                default: return "SmellyType not running"
            }
        }
    }

    Component.onCompleted: {
        // Initial status check
        statusProcess.start("SMELLYTYPE_PATH", ["status"])
    }
}
"##;

/// Generate the QML plugin content with the correct smellytype path
fn get_qml_content() -> String {
    let smellytype_path = get_smellytype_path();
    QML_TEMPLATE.replace("SMELLYTYPE_PATH", &smellytype_path)
}

/// Install DMS integration (create plugin directory and QML file)
pub fn install() -> Result<(), SmellyTypeError> {
    let widget_dir = get_widget_dir();
    let qml_path = get_qml_path();

    // Check if DMS config directory exists
    let dms_config = get_plugins_dir()
        .parent()
        .map(|p| p.to_path_buf())
        .unwrap_or_else(get_plugins_dir);

    if !dms_config.exists() {
        eprintln!("DankMaterialShell config directory not found at:");
        eprintln!("  {}", dms_config.display());
        eprintln!("\nPlease install DankMaterialShell first.");
        return Err(SmellyTypeError::Config(
            "DankMaterialShell config not found".into(),
        ));
    }

    // Check if plugin already exists
    if qml_path.exists() {
        println!("SmellyType widget already exists at:");
        println!("  {}", qml_path.display());
        println!("\nUse --uninstall first if you want to reinstall.");
        return Ok(());
    }

    // Prompt for confirmation
    println!("This will create a DankMaterialShell plugin for SmellyType:");
    println!("  Directory: {}", widget_dir.display());
    println!("  Widget:    {}", qml_path.display());
    print!("\nProceed with installation? [y/N] ");
    io::stdout().flush().unwrap();

    let mut input = String::new();
    io::stdin().read_line(&mut input).unwrap();
    if !input.trim().eq_ignore_ascii_case("y") {
        println!("Installation cancelled.");
        return Ok(());
    }

    // Create plugin directory
    fs::create_dir_all(&widget_dir).map_err(|e| {
        SmellyTypeError::Config(format!("Failed to create plugin directory: {}", e))
    })?;
    println!("Created directory: {}", widget_dir.display());

    // Write QML file
    fs::write(&qml_path, get_qml_content())
        .map_err(|e| SmellyTypeError::Config(format!("Failed to write QML file: {}", e)))?;
    println!("Created widget: {}", qml_path.display());

    println!("\nDankMaterialShell integration installed successfully!");
    println!();
    println!("To enable the widget:");
    println!("  1. Open DankMaterialShell settings");
    println!("  2. Navigate to the Plugins section");
    println!("  3. Enable the SmellyTypeWidget plugin");
    println!("  4. Add the SmellyType widget to your panel");
    println!();
    println!("Note: The widget requires a Nerd Font for icons to display correctly.");
    println!("      If icons appear as boxes, install a Nerd Font:");
    println!("      https://www.nerdfonts.com/");

    Ok(())
}

/// Uninstall DMS integration (remove plugin directory)
pub fn uninstall() -> Result<(), SmellyTypeError> {
    let widget_dir = get_widget_dir();

    if !widget_dir.exists() {
        println!("SmellyType widget not found, nothing to uninstall.");
        return Ok(());
    }

    // Prompt for confirmation
    println!("This will remove the SmellyType widget:");
    println!("  {}", widget_dir.display());
    print!("\nRemove SmellyType from DankMaterialShell? [y/N] ");
    io::stdout().flush().unwrap();

    let mut input = String::new();
    io::stdin().read_line(&mut input).unwrap();
    if !input.trim().eq_ignore_ascii_case("y") {
        println!("Uninstall cancelled.");
        return Ok(());
    }

    // Remove plugin directory
    fs::remove_dir_all(&widget_dir).map_err(|e| {
        SmellyTypeError::Config(format!("Failed to remove plugin directory: {}", e))
    })?;
    println!("Removed: {}", widget_dir.display());

    println!("\nDankMaterialShell integration removed.");
    println!("Restart DankMaterialShell to apply changes.");

    Ok(())
}

/// The simplified QML template for print_config (manual setup instructions)
const QML_SIMPLE_TEMPLATE: &str = r##"import QtQuick
import QtQuick.Layouts

Item {
    id: smellytypeWidget
    implicitWidth: statusText.implicitWidth + 16
    implicitHeight: 32

    property string currentState: "stopped"
    property string statusIcon: "\uf131"
    property color statusColor: "#6272a4"

    readonly property var stateConfig: ({
        "idle": { icon: "\uf130", color: "#50fa7b" },
        "recording": { icon: "\uf111", color: "#ff5555" },
        "transcribing": { icon: "\uf110", color: "#f1fa8c" },
        "stopped": { icon: "\uf131", color: "#6272a4" }
    })

    Timer {
        interval: 500
        running: true
        repeat: true
        onTriggered: statusProcess.start("SMELLYTYPE_PATH", ["status"])
    }

    Process {
        id: statusProcess
        onReadyReadStandardOutput: {
            var output = readAllStandardOutput().toString().trim()
            if (output && output !== currentState) {
                currentState = output
                var config = stateConfig[currentState] || stateConfig["stopped"]
                statusIcon = config.icon
                statusColor = config.color
            }
        }
    }

    Text {
        id: statusText
        anchors.centerIn: parent
        text: statusIcon
        font.family: "Symbols Nerd Font"
        font.pixelSize: 14
        color: statusColor
    }

    MouseArea {
        anchors.fill: parent
        onClicked: toggleProcess.start("SMELLYTYPE_PATH", ["record", "toggle"])
    }

    Process { id: toggleProcess }
}"##;

/// Print DMS configuration instructions
pub fn print_config() {
    let smellytype_path = get_smellytype_path();

    println!("DankMaterialShell Configuration for SmellyType\n");
    println!("============================================\n");

    println!("Run 'smellytype setup dms --install' to automatically install the widget.\n");

    println!("Or manually create the widget:\n");
    println!(
        "1. Create the plugin directory:\n   mkdir -p ~/.config/DankMaterialShell/plugins/SmellyTypeWidget\n"
    );
    println!("2. Create ~/.config/DankMaterialShell/plugins/SmellyTypeWidget/SmellyType.qml\n");
    println!("   with the following content:\n");

    // Print the simplified QML with the actual path substituted
    println!(
        "{}",
        QML_SIMPLE_TEMPLATE.replace("SMELLYTYPE_PATH", &smellytype_path)
    );

    println!("\n\n3. Enable the widget in DankMaterialShell settings.\n");

    println!("---");
    println!("\nRequirements:");
    println!("  - DankMaterialShell installed and running");
    println!("  - Nerd Font installed for icons (https://www.nerdfonts.com/)");
    println!("  - state_file = \"auto\" in smellytype config.toml");
    println!("\nFor more details, see: https://voxtype.io");
}

/// Get the QML content (for programmatic use)
pub fn get_qml_config() -> String {
    get_qml_content()
}
